---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: "Install Apache, GIT, and PHP5"
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - php5
        - php-pear
        - git

    - name: "Turn on Apache and and set it to run on boot"
      service: name={{ item }} state=started enabled=yes
      with_items:
        - apache2
